#!/usr/bin/env bash

DOCKERHUB_NAMESPACE=chenqinghe

images=(
	etcd-amd64:3.1.10
	k8s-dns-dnsmasq-nanny-amd64:1.14.7
	k8s-dns-kube-dns-amd64:1.14.7	
	k8s-dns-sidecar-amd64:1.14.7	
	kube-apiserver-amd64:v1.9.3
	kube-controller-manager-amd64:v1.9.3
	kube-proxy-amd64:v1.9.3
	kube-scheduler-amd64:v1.9.3
	pause-amd64:3.0	
)


for image in ${images[@]}; do
	docker pull $DOCKERHUB_NAMESPACE/$image 
	docker tag $DOCKERHUB_NAMESPACE/$image k8s.gcr.io/$image
	docker rmi $DOCKERHUB_NAMESPACE/$image
done

echo ""
echo ""
echo "Congratulations! All images needed have been installed."
echo ""
